### PR TITLE
Upgrade webpack-bundle-analyzer to version 3.3.2

### PR DESCRIPTION
**Pull request by sdh100shaun**
Addresses alert, updates webpack-bundle-anlayzer

### CODE REVIEW

**Comment by AnnaDodson** [comment]
Would this introduce any breaking changes going from version 2 to version 3?

**Comment by sdh100shaun** [comment]
Does not seem to on my local test of the frontend all builds ok and all MTS components as expected. @AnnaDodson  - worth someone with the full env pulling and checking though

**Comment by AnnaDodson** [comment]
Seems to work ok on mine locally too. LGTM

**Comment by sjduffey** [comment]
Surprised this didn't come up in this: https://github.com/dvsa/front-end/pull/293/commits

But yeah, looks good

**Pull request closed without merging**
